### ISSUE TITLE
Support XDG_CONFIG_HOME environment variable to save config file

### ISSUE THREAD

**Issue by enriquegh** [maxdobeck/sauced#1]
See https://github.com/github/hub/issues/1048

**Comment by maxdobeck** [comment]
XDG_CONFIG_HOME makes sense. Wouldn't be hard to add a check for it.

**Comment by maxdobeck** [comment]
todo added in cmd/root.go

**Comment by mdsauce** [comment]
Added `configUsable()` function to cmd/start.go.  Re-use or copy-paste of logic may be useful when checking for XDG_CONFIG_HOME value.

**Comment by mdsauce** [comment]
closed #38.  Now part of master
