### ISSUE TITLE
Mac OSX - empty lines should be ignored in config file

### ISSUE THREAD

**Issue by mdsauce** [maxdobeck/sauced#10]
Maybe don't use FATAL to report errors when starting tunnels.  This way a GoRoutine can fail gracefully without stopping the entire program from executing.

**Comment by mdsauce** [comment]
Might be happening on other OS's.

Check for newline in start command, also maybe STAT the file and see if the file path is even reachable.

**Comment by maxdobeck** [comment]
Now ignoring empty lines in config file as of https://github.com/maxdobeck/sauced/commit/a734ace40e8637fe47dbc4d7262fdfd62d2a54ee
