### ISSUE TITLE
Main go process exits and forks off SC cmds

### ISSUE THREAD

**Issue by mdsauce** [maxdobeck/sauced#11]
Main process should exit and cede control of the terminal back to the user.  See if forking is possible.

**Comment by mdsauce** [comment]
https://groups.google.com/forum/#!topic/golang-nuts/shST-SDqIp4 <- intercept the CTRL-C (SIGINT) signal and instead of killing parent and children just kill parent.

**Comment by maxdobeck** [comment]
no benefit at the moment.  closing.
