### ISSUE TITLE
refactor and create findTunnel() in state.go

### ISSUE THREAD

**Issue by mdsauce** [maxdobeck/sauced#49]
`findTunnel(state LastKnownTunnels, targetPID int)` should return all available info into a Tunnel object.

It will basically do this loop:
https://github.com/mdsauce/sauced/blob/39bbeb138c92eb8fa0f7268b8fcd09e04cc2a4ee/manager/state.go#L68-L75

**Comment by mdsauce** [comment]
To be clearer the function would be something like:
`findTunnel(state LastKnownTunnels, targetPID int) Tunnel`

This small addition `Tunnel` is the return object.  This means we'll return a Tunnel struct, the in memory logical representation of a Tunnel. 

The parameters passed to the function should remain the same but we should return an object.  The object in question will be used to perform the append to the tunnel state 
`state.Tunnels = append(state.Tunnels[:i], state.Tunnels[i+1:]...) `

Or the removal from tunnel statefile!
`state.Tunnels = append(state.Tunnels[:i], state.Tunnels[i+1:]...)`

But once the we have `findTunnel()` we should be able to simplify the removal or addition of a tunnel from any LastKnownTunnels struct.  

We may even want to consider adding `findTunnel()` as a method.  https://gobyexample.com/methods  For example:
```
somePID := 1234
var tstate LastKnownTunnels
tstate := GetLastKnownState()
tunnel := tstate.findTunnel(somePID)
fmt.Println("Your tunnel: ",  tunnel)
```

@enriquegh it may be prudent to add this as a method but we can always do that work later and you can implement the function as described above (with the `Tunnel` return` of course).

If we take the method route we can also do the same for deletion and maybe creation.
`tstate.deleteTunnel(1234)`
`tstate.createTunnel(some arg, some arg, some other arg)`
and edit so on and so forth.

**Comment by enriquegh** [comment]
This can be closed. Added in #54
