### ISSUE TITLE
Refactor json marshalling and updating of statefile.json

### ISSUE THREAD

**Issue by mdsauce** [maxdobeck/sauced#50]
`updateState()` is poorly named and should be `initState()`.  

/tmp/sauced-state.json  should be updated via a helper function called `saveState()` in most of the state.go funcs that remarshall json.  i.e. if json is remarshalled from a state object LastKnownTunnel then it should be using `saveState()`.

**Comment by mdsauce** [comment]
`saveState()` was used instead fyi.  @enriquegh if that's right this can be closed.

**Comment by enriquegh** [comment]
Yep. saveState now saves the state anytime you need to update it.
InitState was not needed since all updateState was doing was either not used or unnecessary.

This is done.
