### ISSUE TITLE
Refactor LastKnownTunnelState to use Maps instead of a List

### ISSUE THREAD

**Issue by enriquegh** [maxdobeck/sauced#52]
Currently the state of a tunnel is saved as a list in memory.
This is fine but you need to iterate over the whole list every time a tunnel is needed.

Since order doesn't matter, we should implement this as a Map and have the PID (which should be unique) as a key.

This will not only speed up look up time but will allow a tunnel to be added or removed simply by calling

tState.Tunnels.removeTunnel(targetPID)
or even have a tunnel remove itself
tunnel.shutdown()

**Comment by mdsauce** [comment]
For reference https://gobyexample.com/maps.  Like it says on the page this is basically a Hash or a dictionary.  Same concept.  Key Value data structure.

In this case I also agree a PID is a safe Key to use.  AssignedID should also be safe to use as a key if you encounter any problems

**Comment by mdsauce** [comment]
Is this still prudent and active?

**Comment by enriquegh** [comment]
Added stretch label. I will close this. If we ever get to a point where this is causing performance issues we can revisit it.
