### ISSUE TITLE
Add Lock to Updates on the IPC file

### ISSUE THREAD

**Issue by mdsauce** [maxdobeck/sauced#62]
Added this todo
	// TODO Obtain a lock on the file THEN add to the statefile

For the `AddTunnel()` func.  It should obtain a lock on the Inter Process Communication IPC file and gracefully make Additions.  So as not to compete with other processes.

Specifically here:
https://github.com/mdsauce/sauced/blob/061fcbc1311e3e1629e4745c6d3fdf951227d81b/manager/state.go#L91

**Comment by maxdobeck** [comment]
Alternative is a channel that recvs writes for the file. One go routine can read from the channel. All writes will be sequential.

**Comment by mdsauce** [comment]
🤷‍♂ not really a big deal yet fyi.  I just threw a randomized sleep in there and everything's been fine.  reopen if this is an issue
